services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - flask
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  flask:
    build: ./python-server
    ports:
      - "5050:5050"
    depends_on:
      - redis
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - LLAMA2_MODEL_PATH=${LLAMA2_MODEL_PATH}
      - MISTRAL_MODEL_PATH=${MISTRAL_MODEL_PATH}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
